openapi: 3.1.0
info:
  title: Token
  version: 2.0.0
  description: Schema definition for the Token entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    Token:
      type: object
      title: Token
      description: >
        Attributes for the Token entity in the Beckn Mobility domain.
      properties: {}
