openapi: 3.1.0
info:
  title: PaymentTransaction
  version: 2.0.0
  description: Schema definition for the PaymentTransaction entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    PaymentTransaction:
      type: object
      title: PaymentTransaction
      description: >
        Attributes for the PaymentTransaction entity in the Beckn Mobility domain.
      properties: {}
