openapi: 3.1.0
info:
  title: ItineraryElement
  version: 2.0.0
  description: Schema definition for the ItineraryElement entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    ItineraryElement:
      type: object
      title: ItineraryElement
      description: >
        Attributes for the ItineraryElement entity in the Beckn Mobility domain.
      properties: {}
