openapi: 3.1.0
info:
  title: Message
  version: 2.0.0
  description: Schema definition for the Message entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    Message:
      type: object
      title: Message
      description: >
        Attributes for the Message entity in the Beckn Mobility domain.
      properties: {}
