openapi: 3.1.0
info:
  title: PlaceRequest
  version: 2.0.0
  description: Schema definition for the PlaceRequest entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    PlaceRequest:
      type: object
      title: PlaceRequest
      description: >
        Attributes for the PlaceRequest entity in the Beckn Mobility domain.
      properties: {}
