openapi: 3.1.0
info:
  title: Geography
  version: 2.0.0
  description: Schema definition for the Geography entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    Geography:
      type: object
      title: Geography
      description: >
        Attributes for the Geography entity in the Beckn Mobility domain.
      properties: {}
