openapi: 3.1.0
info:
  title: ServiceDelivery
  version: 2.0.0
  description: Schema definition for the ServiceDelivery entity in the Beckn Mobility
  license:
    name: CC-BY-NC-SA 4.0 International
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    ServiceDelivery:
      type: object
      title: ServiceDelivery
      description: The top-level response container in SIRI encapsulating one or more
        real-time data delivery types.
      x-tags:
        - mobility
        - ride-hailing
      properties:
        responseTimestamp:
          description: Timestamp when this service delivery was generated
          type: string
          format: date-time
        producerRef:
          description: Identifier of the system producing this delivery
          type: string
        requestMessageRef:
          description: Reference to the request that triggered this delivery
          type: string
        stopMonitoring:
          description: Stop monitoring delivery payloads
          $ref: https://schema.beckn.io/StopMonitoring/v2.0/attributes.yaml#/components/schemas/StopMonitoring
        vehicleMonitoring:
          description: Vehicle monitoring delivery payloads
          $ref: https://schema.beckn.io/VehicleMonitoringDelivery/v2.0/attributes.yaml#/components/schemas/VehicleMonitoringDelivery
        estimatedTimetable:
          description: Estimated timetable delivery payloads
          $ref: https://schema.beckn.io/EstimatedTimetableDelivery/v2.0/attributes.yaml#/components/schemas/EstimatedTimetableDelivery
        id:
          description: Unique identifier for the catalog
          type: string
        descriptor:
          description: Human-readable description of the catalog
          $ref: https://schema.beckn.io/core/v2.0/Descriptor/attributes.yaml#components/schemas/Descriptor
        tags:
          description: Tags associated with the catalog
          type: string
      additionalProperties: false
