openapi: 3.1.0
info:
  title: AncillaryService
  version: 2.0.0
  description: Schema definition for the AncillaryService entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    AncillaryService:
      type: object
      title: AncillaryService
      description: >
        Attributes for the AncillaryService entity in the Beckn Mobility domain.
      properties: {}
