openapi: 3.1.0
info:
  title: Reservation
  version: 2.0.0
  description: Schema definition for the Reservation entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    Reservation:
      type: object
      title: Reservation
      description: >
        Attributes for the Reservation entity in the Beckn Mobility domain.
      properties: {}
