openapi: 3.1.0
info:
  title: VehicleMonitoringDelivery
  version: 2.0.0
  description: Schema definition for the VehicleMonitoringDelivery entity in the Beckn
  license:
    name: CC-BY-NC-SA 4.0 International
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    VehicleMonitoringDelivery:
      type: object
      title: VehicleMonitoringDelivery
      description: A real-time data delivery providing current positions and operational
        states of a set of vehicles.
      x-tags:
        - mobility
        - ride-hailing
      properties:
        responseTimestamp:
          description: Timestamp of this monitoring delivery
          type: string
          format: date-time
        vehicleActivities:
          description: List of vehicle activity records in this delivery
          $ref: https://schema.beckn.io/MonitoredVehicleJourney/v2.0/attributes.yaml#/components/schemas/MonitoredVehicleJourney
        validUntil:
          description: Time until which this delivery data is valid
          type: string
          format: date-time
        id:
          description: Unique identifier for the tracking record
          type: string
        url:
          description: URL endpoint for real-time tracking information
          type: string
          format: uri
        status:
          description: Current tracking status
          $ref: https://schema.beckn.io/State/v2.0/attributes.yaml#/components/schemas/State
        validity:
          description: Validity period for this tracking record
          $ref: https://schema.beckn.io/TimePeriod/v2.0/attributes.yaml#/components/schemas/TimePeriod
      additionalProperties: false
