openapi: 3.1.0
info:
  title: TransportationComplex
  version: 2.0.0
  description: Schema definition for the TransportationComplex entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    TransportationComplex:
      type: object
      title: TransportationComplex
      description: >
        Attributes for the TransportationComplex entity in the Beckn Mobility domain.
      properties: {}
