openapi: 3.1.0
info:
  title: Journey
  version: 2.0.0
  description: Schema definition for the Journey entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    Journey:
      type: object
      title: Journey
      description: >
        Attributes for the Journey entity in the Beckn Mobility domain.
      properties: {}
