openapi: 3.1.0
info:
  title: SecurityScheme
  version: 2.0.0
  description: Schema definition for the SecurityScheme entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    SecurityScheme:
      type: object
      title: SecurityScheme
      description: >
        Attributes for the SecurityScheme entity in the Beckn Mobility domain.
      properties: {}
