openapi: 3.1.0
info:
  title: Offer
  version: 2.0.0
  description: Schema definition for the Offer entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    Offer:
      type: object
      title: Offer
      description: >
        Attributes for the Offer entity in the Beckn Mobility domain.
      properties: {}
