openapi: 3.1.0
info:
  title: ChargeDetailRecord
  version: 2.0.0
  description: Schema definition for the ChargeDetailRecord entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    ChargeDetailRecord:
      type: object
      title: ChargeDetailRecord
      description: >
        Attributes for the ChargeDetailRecord entity in the Beckn Mobility domain.
      properties: {}
