openapi: 3.1.0
info:
  title: Line
  version: 2.0.0
  description: Schema definition for the Line entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    Line:
      type: object
      title: Line
      description: >
        Attributes for the Line entity in the Beckn Mobility domain.
      properties: {}
