openapi: 3.1.0
info:
  title: OperationalPoint
  version: 2.0.0
  description: Schema definition for the OperationalPoint entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    OperationalPoint:
      type: object
      title: OperationalPoint
      description: >
        Attributes for the OperationalPoint entity in the Beckn Mobility domain.
      properties: {}
