openapi: 3.1.0
info:
  title: FareLegRule
  version: 2.0.0
  description: Schema definition for the FareLegRule entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    FareLegRule:
      type: object
      title: FareLegRule
      description: >
        Attributes for the FareLegRule entity in the Beckn Mobility domain.
      properties: {}
