openapi: 3.1.0
info:
  title: TransportNetwork
  version: 2.0.0
  description: Schema definition for the TransportNetwork entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    TransportNetwork:
      type: object
      title: TransportNetwork
      description: >
        Attributes for the TransportNetwork entity in the Beckn Mobility domain.
      properties: {}
