openapi: 3.1.0
info:
  title: Frequency
  version: 2.0.0
  description: Schema definition for the Frequency entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    Frequency:
      type: object
      title: Frequency
      description: >
        Attributes for the Frequency entity in the Beckn Mobility domain.
      properties: {}
