openapi: 3.1.0
info:
  title: AuxiliaryTrafficArea
  version: 2.0.0
  description: Schema definition for the AuxiliaryTrafficArea entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    AuxiliaryTrafficArea:
      type: object
      title: AuxiliaryTrafficArea
      description: >
        Attributes for the AuxiliaryTrafficArea entity in the Beckn Mobility domain.
      properties: {}
