openapi: 3.1.0
info:
  title: AirRoute
  version: 2.0.0
  description: Schema definition for the AirRoute entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    AirRoute:
      type: object
      title: AirRoute
      description: >
        Attributes for the AirRoute entity in the Beckn Mobility domain.
      properties: {}
