openapi: 3.1.0
info:
  title: BaggageAllowance
  version: 2.0.0
  description: Schema definition for the BaggageAllowance entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BaggageAllowance:
      type: object
      title: BaggageAllowance
      description: >
        Attributes for the BaggageAllowance entity in the Beckn Mobility domain.
      properties: {}
