openapi: 3.1.0
info:
  title: Mobility
  version: 2.0.0
  description: Schema definition for the Mobility entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA 4.0 International
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Mobility:
      type: object
      title: Mobility
      description: Attributes for the Mobility entity in the Beckn Mobility domain.
      x-tags:
        - mobility
        - ride-hailing
      properties: {}
      additionalProperties: false
