openapi: 3.1.0
info:
  title: FlightSegment
  version: 2.0.0
  description: Schema definition for the FlightSegment entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    FlightSegment:
      type: object
      title: FlightSegment
      description: >
        Attributes for the FlightSegment entity in the Beckn Mobility domain.
      properties: {}
