openapi: 3.1.0
info:
  title: Railway
  version: 2.0.0
  description: Schema definition for the Railway entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    Railway:
      type: object
      title: Railway
      description: >
        Attributes for the Railway entity in the Beckn Mobility domain.
      properties: {}
