openapi: 3.1.0
info:
  title: BasicSafetyMessage
  version: 2.0.0
  description: Schema definition for the BasicSafetyMessage entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    BasicSafetyMessage:
      type: object
      title: BasicSafetyMessage
      description: >
        Attributes for the BasicSafetyMessage entity in the Beckn Mobility domain.
      properties: {}
