openapi: 3.1.0
info:
  title: EventStream
  version: 2.0.0
  description: Schema definition for the EventStream entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    EventStream:
      type: object
      title: EventStream
      description: >
        Attributes for the EventStream entity in the Beckn Mobility domain.
      properties: {}
