openapi: 3.1.0
info:
  title: RightSpecification
  version: 2.0.0
  description: Schema definition for the RightSpecification entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    RightSpecification:
      type: object
      title: RightSpecification
      description: >
        Attributes for the RightSpecification entity in the Beckn Mobility domain.
      properties: {}
